"""
This type stub file was generated by pyright.
"""

from .color import Color
from .easings import ease_in, ease_in_out, ease_out, linear
from .deltae import cie1976, cie1994g, cie1994t, ciede2000, euclid
from .attr import Blue, Green, Hue, Lightness, Luma, Red, Saturation
from .types import CMY, CMYK, HLS, HSV, Lab, Luv, RGB, XYZ, YIQ, YUV
from .tables import NAMED_COLORS

"""
The colorzero package defines a number of classes for representation and
manipulation of colors. The primary class of interest to users is
:class:`Color`.  The other classes are used for manipulation of the attributes
on this class and are:

* :class:`Red`
* :class:`Green`
* :class:`Blue`
* :class:`Hue`
* :class:`Lightness`
* :class:`Saturation`
* :class:`Luma`
"""
