"""
This type stub file was generated by pyright.
"""

"Defines various easing functions for :meth:`Color.gradient`."
def linear(steps): # -> Generator[Any, Any, None]:
    "Linear easing function; yields *steps* values between 0.0 and 1.0"
    ...

def ease_in(steps): # -> Generator[Any, Any, None]:
    "Quadratic ease-in function; yields *steps* values between 0.0 and 1.0"
    ...

def ease_out(steps): # -> Generator[Any, Any, None]:
    "Quadratic ease-out function; yields *steps* values between 0.0 and 1.0"
    ...

def ease_in_out(steps): # -> Generator[Any, Any, None]:
    "Quadratic ease-in-out function; yields *steps* values between 0.0 and 1.0"
    ...

