"""
This type stub file was generated by pyright.
"""

"""
Defines the available color names, derived from the `CSS Color Module`_ Level 3
Specification, section 4.3, along with tables for the original DOS colors, and
XTerm colors (for :func:`format` output).

.. _CSS Color Module: http://www.w3.org/TR/css3-color/#svg-color
"""
DOS_COLORS = ...
XTERM_COLORS = ...
NAMED_COLORS = ...
